apiRules:
- exclude:
    uidRegex: ^System\.Object
- exclude:
    uidRegex: ^ToSic\.Razor\.Dnn
- exclude: 
    uidRegex: ^ToSic\.Razor\.Html$
- exclude: 
    uidRegex: ^ToSic\.Razor\.Interfaces
- exclude: 
    uidRegex: ^ToSic\.Razor\.Internals