apiRules:
# Exclude System.Object to avoid having .Equals and stuff
# in the documentation
- exclude:
    uidRegex: ^System\.Object

# Exclude the DNN specific implementation
# This namespace isn't for public use, as anything we do should be interface typed
- exclude:
    uidRegex: ^ToSic\.Razor\.Dnn

# Hide internal APIs which we need, but the signature may change at any time
- exclude: 
    uidRegex: ^ToSic\.Razor\.Internals


# Exclude anything marked as PrivateApi
# In future, we may change this to only show things which are PublicApi (recommendation of iJungleboy)
- exclude:
    hasAttribute:
      uid: ToSic.Razor.Internals.Documentation.PrivateApi